#! /bin/sh

$HOME/.config/polybar/launch.sh &

#restores previously chosen nitrogen wallpaper
nitrogen --restore &

#starts up picom's config file
pkill picom
picom --experimental-backends -b

#starts up platerctld
playerctl daemon &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         4
bspc config window_gap          24

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Spotify desktop='^4'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
